spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:~/test
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
